language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - 0.4
    - nightly
notifications:
  email: false
sudo: required
dist: trusty

after_success:
  - julia -e 'Pkg.clone("https://github.com/JuliaDocs/Documenter.jl")'
  - julia -e 'cd(Pkg.dir("Polynomials")); include(joinpath("docs", "make.jl"))'
